### ISSUE TITLE
From Open Source to freelancer

### ISSUE THREAD

**Issue by franciscop** [tokyojs/talks#8]
# From Open Source to freelancer

### Introduction

I have launched many open source projects with varying degrees of popularity, including [Picnic CSS](http://picnicss.com/) and [Umbrella JS](http://umbrellajs.com/). After the last one was launched, a company from US contacted me and I've been working as a freelancer ever since. I made the front-end of http://angularattack.com/, and worked with other people on Andreessen Horowitz and Sequoia Capital websites.

***

Alternative

***

# Doing horrible things to Javascript

### Introduction

I love playing with Javascript. This includes testing its limits and reaching to places better left alone, so I'd love to show a bit of it. Modifying the prototypes is common but I did it in a way that haven't been talked about but that yield surprisingly clean code. Please don't use it in production (;

### Presentation Details
**Speaker Name**: Francisco Presencia
**Duration**: 20min

## Extra

- I am leaving Japan around the beginning-middle of September, I don't have my ticket out yet. Please ping github when the date is accepted so I'll update it to say if I'm available or not.

- I'd love to just go there if there's no available spot for a talk or the proposed topics aren't welcome.

**Comment by bucaran** [comment]
Thanks for your submission.

> From Open Source to freelancer

Sounds cool man. 

> Please ping github when the date is accepted so I'll update it to say if I'm available or not.

Will do. I should report back in a few days!

**Comment by franciscop** [comment]
Awesome @bucaran, updated accordingly. Though it's a pity as I will have to cut off some of the advice about company setup since I'm based on Europe.

**Comment by bucaran** [comment]
> Doing horrible things to Javascript

Curious about that one too :)

@briandeheus Any you want to add?

**Comment by franciscop** [comment]
That one would be about making things like this work (it *is* valid JS):

```js
'.button'.click(e => alert(e.target.innerHTML));
```

**Comment by bucaran** [comment]
Are you extending the String prototype with a `click` method and then parsing string's value to select elements of class `.button`?

That's fun. I wonder how far you could take this idea.

**Comment by franciscop** [comment]
Exactly, similar to:

```js
var boolish = true;
boolish
  .then(() => alert('hi'))
  .else(() => alert('bye'));
```

**Comment by bucaran** [comment]
@franciscop Haha, the boolean one is pretty clever.

**Comment by franciscop** [comment]
Unfortunately I am leaving in a couple of days so I'm closing this issue, maybe next time I visit Tokyo :smile:

**Comment by jbucaran** [comment]
No worries. Hope you had a great time in Tokyo.
